version: "3"

silent: true

tasks:
  default:
    cmd: task --list

  test:
    desc: Run unit tests
    cmd: clojure -X:test

  test:watch:
    desc: Watch source code and run tests accordingly
    cmd: clojure -X:test:watcher

  lint:
    desc: Lint source code
    cmds:
      - task: lint:kondo
      - task: lint:splint

  lint:kondo:
    desc: Lint source code using clj-kondo
    cmd: rg -tclojure -tedn --files | xargs clj-kondo --parallel --lint

  lint:splint:
    desc: Lint source code using splint
    cmd: clojure -M:splint

  check:
    desc: Check for reflection using clj-check
    cmd: clojure -M:check

  editorconfig:
    desc: Check for editorconfig violations using editorconfig-checker
    cmd: editorconfig-checker

  install:
    desc: Install locally
    cmd: clojure -T:build install

  publish:
    desc: Deploy to Clojars
    cmd: clojure -T:build deploy
