version: "3"

silent: true

tasks:
  default:
    cmds:
      - task --list

  test:
    desc: Run unit tests
    cmds:
      - clojure -X:test

  test:watch:
    desc: Watch source code and run tests accordingly
    cmds:
      - clojure -X:test:watcher

  lint:
    desc: Lint code using clj-kondo
    cmds:
      - rg -tclojure -tedn --files | xargs clj-kondo --parallel --lint

  check:
    desc: Check for reflection using clj-check
    cmds:
      - clojure -M:check

  editorconfig:
    desc: Check for editorconfig violations using editorconfig-checker
    cmds:
      - git ls-files | xargs editorconfig-checker

  install:
    desc: Install locally
    cmds:
      - clojure -T:build install

  publish:
    desc: Deploy to Clojars
    cmd:
      - clojure -T:build deploy
