name: editorconfig
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  editorconfig:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install editorconfig-checker
        uses: editorconfig-checker/action-editorconfig-checker@main

      - name: Install just Task Runner
        uses: extractions/setup-just@v1

      - name: Run editorconfig-checker
        run: just editorconfig
