name: lint
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install Clojure CLI Tools
        uses: DeLaGuardo/setup-clojure@12.5
        with:
          cli: latest
          clj-kondo: latest

      - name: Cache dependencies
        uses: actions/cache@v4
        id: cache
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.clojure
            ~/.cpcache
          key: clojure-m2-${{ hashFiles('deps.edn') }}

      - name: Prep library
        if: steps.cache.outputs.cache-hit != 'true'
        run: clojure -P -X:check:test

      - name: Install ripgrep
        run: sudo apt-get install ripgrep

      - name: Install Mise
        uses: jdx/mise-action@v2
        with:
          experimental: true

      - name: Run Linter
        run: mise run lint:all
