name: lint
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Install Clojure CLI Tools
        uses: DeLaGuardo/setup-clojure@9.4
        with:
          cli: latest
          clj-kondo: latest

      - name: Cache dependencies
        uses: actions/cache@v3
        id: cache
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.clojure
            ~/.cpcache
          key: clojure-m2-${{ hashFiles('deps.edn') }}

      - name: Prep library
        if: steps.cache.outputs.cache-hit != 'true'
        run: clojure -P -X:check:test

      - name: Install ripgrep
        run: sudo apt-get install ripgrep

      - name: Install just Task Runner
        uses: extractions/setup-just@v1

      - name: Run Linter
        run: just lint
