name: test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Prepare Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17

      - name: Install Clojure CLI Tools
        uses: DeLaGuardo/setup-clojure@13.4
        with:
          cli: latest

      - name: Cache dependencies
        uses: actions/cache@v4
        id: cache
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.clojure
            ~/.cpcache
          key: clojure-m2-${{ hashFiles('deps.edn') }}

      - name: Prep library
        if: steps.cache.outputs.cache-hit != 'true'
        run: clojure -P -X:check:test

      - name: Install Mise
        uses: jdx/mise-action@v3
        with:
          experimental: true

      - name: Install just
        uses: extractions/setup-just@v3

      - name: Run Unit Tests
        run: just test
