name: test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install Clojure CLI Tools
        uses: DeLaGuardo/setup-clojure@12.5
        with:
          cli: latest

      - name: Cache dependencies
        uses: actions/cache@v4
        id: cache
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.clojure
            ~/.cpcache
          key: clojure-m2-${{ hashFiles('deps.edn') }}

      - name: Prep library
        if: steps.cache.outputs.cache-hit != 'true'
        run: clojure -P -X:check:test

      - name: Install Task
        uses: arduino/setup-task@v2

      - name: Run Unit Tests
        run: task test
