name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Install Clojure CLI Tools
        uses: DeLaGuardo/setup-clojure@5.1
        with:
          cli: latest

      - name: Cache local Maven repository
        uses: actions/cache@v3
        id: cache
        with:
          path: ~/.m2
          key: clojure-m2-${{ hashFiles('deps.edn') }}

      - name: Prep library
        if: steps.cache.outputs.cache-hit != 'true'
        run: clojure -P

      - name: Install just Task Runner
        uses: extractions/setup-just@v1

      - name: Run Unit Tests
        run: just test
